### ISSUE TITLE
Infragistics file is taking huge time lo load and its impacting performance

### ISSUE THREAD

**Issue by kirantp20** [RevealBi/reveal-sdk-canary-samples#1]
Hello,

I am trying an angular app to load Reveal BI JS client in my local and the file itself is around 13 MB and its taking too much time to load `infragistics.reveal.js` file in my local/dev server. I've tried to split the file but with no help. This is a serious performance issue and needs attention. Please suggest any hacks to fix this issue. 

TIA.

**Comment by brianlagunas** [comment]
You are posting this question in the wrong repo.

However, here are some things you can try.

- Serve the file over your CDN
- Try loading it asynchronously by using the async attribute
- Prioritize the loading, maybe use the defer attribute
- Leverage the browser cache by setting the appropriate headers

These are just some standard strategies to handling large JS files. There are more, so I would recommend you favorite search engine to find them.
